default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bitgrabbers_development # ediermes_development #bsmartweb_development #bsmartweb_development #bsmartweb_staging #bsmartweb_development #whitelabel_hachette_production
  username: oscar.riva
  password: Wintermute50
  host: localhost

test:
  <<: *default
  database: bitgrabbers_test
  username:
  password:
  host: localhost

production:
  <<: *default
  database: bitgrabbers
  username: pi
  password: sh1r0w76!
  host: localhost